name: Cloud Sideloadly PROD
on:
  workflow_dispatch:
    inputs:
      apple_id:
        description: 'Apple ID'
        required: true
      apple_password:
        description: 'App-Specific Password'
        required: true
      fake_name:
        description: 'Stealth Name'
        required: false
        default: 'Calculator'

jobs:
  sideload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libimobiledevice-utils ideviceinstaller jq curl socat strongswan libcharon-extra-plugins libcharon-extauth-plugins
          
          # Install Cloudflare WARP
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update
          sudo apt-get install -y cloudflare-warp
          
          # Install zsign binary
          curl -L -o zsign https://github.com/zhlynn/zsign/releases/download/v1.1.2/zsign_linux_x86_64
          sudo mv zsign /usr/local/bin/ && sudo chmod +x /usr/local/bin/zsign
          
          # Install netmuxd
          curl -L -o netmuxd https://github.com/jkcoxson/netmuxd/releases/download/v0.1.4/x86_64-linux-netmuxd
          sudo mv netmuxd /usr/local/bin/ && sudo chmod +x /usr/local/bin/netmuxd
          
      - name: Launch Ultra Engine
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          APPLE_ID: ${{ github.event.inputs.apple_id }}
          APPLE_PASSWORD: ${{ github.event.inputs.apple_password }}
          FAKE_NAME: ${{ github.event.inputs.fake_name }}
          UDID: ${{ secrets.UDID }}
        run: |
          python3 -u scripts/engine.py --mode sideload
